default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

development:
  <<: *default
  database: library

test:
  <<: *default
  database: library_test

# Override with DATABASE_URL
production:
  primary: &primary_production
    <<: *default
    database: backend_production
    username: backend
    password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: backend_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: backend_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: backend_production_cable
    migrations_paths: db/cable_migrate
